### ISSUE TITLE
Membership Add Role cannot see dropdown contents

### ISSUE THREAD

**Issue by karlnicholas** [openshift/origin-web-console#2614]
When attempting to add a another role in openshift online membership screen you cannot see the description of the roles.

![image](https://user-images.githubusercontent.com/2110283/34463953-086f1920-ee22-11e7-8185-92a42acf364c.png)

**Comment by spadgett** [comment]
Should be fixed by #2402 since these system roles will be hidden.

**Comment by spadgett** [comment]
@karlnicholas Can I ask which Online cluster you saw this on?

**Comment by karlnicholas** [comment]
I was on pro-us-east-1.

**Comment by benjaminapetersen** [comment]
Descriptions do wrap:
![screen shot 2018-01-02 at 2 11 06 pm](https://user-images.githubusercontent.com/280512/34496237-cc674096-efc6-11e7-9040-4f8ed513deaa.png)

And tablet/mobile view has a better view of the long names, though still not perfect:
![screen shot 2018-01-02 at 2 12 11 pm](https://user-images.githubusercontent.com/280512/34496293-f3fc142e-efc6-11e7-9e2c-722f246361b0.png)

**Comment by spadgett** [comment]
If we could find a way to make the dropdown wider at desktop, I think it would help generally. The description wrap, but they are long enough that you only see a few items at a time. And of course in this case the names are cut off at desktop.

**Comment by benjaminapetersen** [comment]
Yeah I'm tinkering with that a little bit.  Not sure if we should make it wider, or wrap them (kinda ugly).  I'm guessing the max char length possible is quite high...

**Comment by spadgett** [comment]
We could also add a `title` attribute to the elements so at least you can hover and see.

Related to #1219

**Comment by spadgett** [comment]
@openshift/team-ux-review

**Comment by benjaminapetersen** [comment]
I'm inclined that way as well.  Is a bit annoying, but there would certainly be a way to see the entire name no matter the length then.

**Comment by spadgett** [comment]
It'd be a stop gap fix until we can do something better. It's not a great user experience if you need to hover over every item, but at least you can see.

**Comment by ncameronbritt** [comment]
Something similar to what @beanh66 proposed for [adding labels](http://openshift.github.io/openshift-origin-design/web-console/project-details/labels#add-labels) could be a possibility. Rather than having the selector as part of the table, an "add role" action could bring up a modal. That might more easily accommodate longer names and make the descriptions easier to read.

**Comment by rhamilto** [comment]
Any objections to eliminating the three column layout at desktop resolutions to resolve the bug as an interim solution?

Note:  this is a rough mock
<img width="1426" alt="screen shot 2018-02-27 at 10 28 50 am" src="https://user-images.githubusercontent.com/895728/36737444-0cdcd420-1ba9-11e8-82b8-12a4549b2e92.PNG">

**Comment by sg00dwin** [comment]
+1 works for me

**Comment by benjaminapetersen** [comment]
not a prob imo.
